#!/usr/bin/env bash

SSH_URL="git@github.com:"
DOT_GIT=".git"

main() {
    remote=$(git config remote.origin.url 2>/dev/null)

    if [ -z "$remote" ]; then
        echo "Error: remote URL not found."
        return 1
    fi

    if [[ $remote == "$SSH_URL"* ]]; then
        remote="${remote#${SSH_URL}}"
    fi

    if [[ $remote == *"$DOT_GIT" ]]; then
        remote="${remote%$DOT_GIT}"
    fi

    echo "https://github.com/$remote"
    return 0
}

main "$@"
