#!/usr/bin/env python3
from __future__ import annotations

import argparse
import subprocess

SSH_URL = 'git@github.com:'
DOT_GIT = '.git'


def main(argv=None) -> int:
    parser = argparse.ArgumentParser()
    parser.parse_args(argv)

    cmd = ('git', 'config', 'remote.origin.url')
    try:
        remote = subprocess.check_output(cmd, encoding='UTF-8').strip()

        if remote.startswith(SSH_URL):
            remote = remote[len(SSH_URL):]
        if remote.endswith(DOT_GIT):
            remote = remote[:-1 * len(DOT_GIT)]

        print(f'https://github.com/{remote}')
        return 0
    except subprocess.CalledProcessError:
        print('Error: remote URL not found.')
        return 1


if __name__ == '__main__':
    raise SystemExit(main())
