#!/usr/bin/env python3
from __future__ import annotations

import argparse
import sys

import requests


def main(argv=None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('lang')
    args = parser.parse_args(argv)

    lang = args.lang.capitalize()
    url = f'https://raw.githubusercontent.com/github/gitignore/main/{lang}.gitignore'

    try:
        response = requests.get(url)
        response.raise_for_status()

        with open('.gitignore', 'w') as f:
            f.write(response.text)
        print(f'.gitignore for {lang} downloaded successfully.')

        return 0
    except Exception:
        print(f'Error: A .gitignore was not found for {lang}', file=sys.stderr)
        return 1


if __name__ == '__main__':
    raise SystemExit(main())
